apps/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.LoginView.as_view(), name='login'),
  path('register/', views.RegisterView.as_view(), name='register'),
  path('logout/', views.logoutUser, name='logout'),
]

apps/events/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('events/', views.EventsView.as_view(), name='list'),
  path('events/create', views.EventCreate.as_view(), name='create'),
  path('events/<int:event_id>', views.EventDetail.as_view(), name='detail'),
  path('events/enroll', views.EventEnrollCreate.as_view(), name='enroll'),
  path('events/my_enrollments', views.MyEnrolledEvents.as_view(), name='my_enrollments'),
]

events_manage/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.authentication import views

urlpatterns = [
  path('admin/', admin.site.urls),

  # Authentication
  path('', include(('apps.authentication.urls', 'authentication'), namespace='authentication')),

  # Events
  path('', include(('apps.events.urls', 'events'), namespace='events')),
]

apps/authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.utils import timezone


class MyUserManager(BaseUserManager):
  def create_user(self, email, password=None, **extra_fields):
    if not email:
      raise ValueError('The Email field must be set')

    email = self.normalize_email(email)

    extra_fields.setdefault('date_joined', timezone.now())
    extra_fields.setdefault('is_active', True)

    user = self.model(email=email, **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self, email, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)

    return self.create_user(email, password, **extra_fields)


# Create your models here.
class User(AbstractUser):
  username = None
  name = models.CharField(max_length=200)
  email = models.EmailField(max_length=50, unique=True)
  password = models.CharField(max_length=200)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = []

  objects = MyUserManager()

  def __str__(self) -> str:
    return self.email

  class Meta:
    db_table = 'user'
    verbose_name = 'user'
    verbose_name_plural = 'users'

apps/events/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Event(models.Model):
  name = models.CharField(max_length=200)
  description = models.CharField(max_length=255)
  location = models.CharField(max_length=200)
  date_time = models.DateTimeField(auto_created=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  def __str__(self) -> str:
    return self.name

  class Meta:
    db_table = 'event'
    verbose_name = 'event'
    verbose_name_plural = 'events'


class Enrollment(models.Model):
  event = models.ForeignKey(Event, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  date = models.DateTimeField(auto_created=True)

  def __str__(self) -> str:
    return self.event

  class Meta:
    db_table = 'enrollment'
    verbose_name = 'enrollment'
    verbose_name_plural = 'enrollments'

apps/authentication/forms.py
from django import forms

class UserLoginForm(forms.Form):
  email = forms.EmailField(required=True)
  password = forms.CharField(widget=forms.PasswordInput, required=True)

class UserRegisterForm(forms.Form):
  name = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  password = forms.CharField(widget=forms.PasswordInput, required=True)

apps/events/forms.py
from django.forms import ModelForm
from .models import Event, Enrollment

class EventForm(ModelForm):
  class Meta:
    model = Event
    fields = [
      'name',
      'description',
      'location',
      'date_time',
    ]


class EnrollmentForm(ModelForm):
  class Meta:
    model = Enrollment
    fields = ['event', 'date']

apps/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .models import User
from .forms import UserLoginForm, UserRegisterForm

# Create your views here.
class LoginView(View):
    template_name = 'login.html'
    form_class = UserLoginForm

    def get(self, request):
      form = self.form_class()
      return render(request, self.template_name, { 'form': form })

    def post(self, request):
      form = self.form_class(request.POST)

      if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(request, username=email, password=password)

        if user is not None:
          login(request, user)
          return redirect('events:list')

        return render(request, self.template_name, { 'form': form, 'error': 'Email and/or password is incorrect' })

      return render(request, self.template_name, { 'form': form, 'error': 'Fields are requireds' })


class RegisterView(View):
  template_name = 'register.html'
  form_class = UserRegisterForm

  def get(self, request):
    form = self.form_class()
    return render(request, self.template_name, { 'form': form })

  def post(self, request):
    form = self.form_class(request.POST)

    if form.is_valid():
      name = form.cleaned_data.get('name')
      email = form.cleaned_data.get('email')
      password = form.cleaned_data.get('password')

      user = User.objects.create_user(name=name, email=email, password=password)

      login(request, user)
      return redirect('events:list')

    return render(request, self.template_name, { 'form': form, 'error': 'Fields are requireds' })


def logoutUser(request):
  logout(request)
  return redirect('authentication:login')

apps/events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, View
from .models import Event, Enrollment
from .forms import EventForm, EnrollmentForm

# Create your views here.
class EventsView(ListView):
  model = Event
  template_name = 'list_events.html'
  context_object_name = 'events_data'


class EventCreate(CreateView):
  model = Event
  form_class = EventForm
  template_name = 'create_event.html'
  success_url = reverse_lazy('events:list')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class EventDetail(View):
  model = Event
  template_name = 'event_detail.html'

  def get(self, request, event_id):
    event = self.model.objects.get(id=event_id)

    if event is not None:
      return render(request, self.template_name, { 'event': event })

    return redirect('events:list')


class EventEnrollCreate(CreateView):
  model = Enrollment
  form_class = EnrollmentForm
  template_name = 'event_enroll.html'
  success_url = reverse_lazy('events:my_enrollments')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class MyEnrolledEvents(View):
  model = Enrollment
  template_name = 'list_enrolled_events.html'

  def get(self, request):
    user = self.request.user
    enrollments = self.model.objects.filter(user=user)

    enrolled_events = [enrollment.event for enrollment in enrollments]

    return render(request, self.template_name, { 'enrolled_events': enrolled_events })

apps/authentication/templates/login.html
{% extends 'auth_layout.html' %}
{% load widget_tweaks %}
{% block title %} Iniciar Sesión {% endblock %}

{% block content %}
<h1 class="font-bold px-5 text-3xl text-gray-700 mb-5">Inicia Sesión</h1>

{% if error %}
  <div class="flex items-center py-2 px-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium block">Error!</span>
      <p>{{ error }}</p>
    </div>
  </div>
{% endif %}

<div class="bg-white shadow-sm w-full rounded-lg divide-y divide-gray-200">
  <form class="px-5 py-7" method="POST">
    {% csrf_token %}

    <div class="flex flex-col gap-2 mb-5">
      <label for="id_email" class="font-semibold text-sm text-gray-500 block">
        Correo electrónico
      </label>

      {% render_field form.email type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" autofocus=true %}
    </div>

    <div class="flex flex-col gap-2 mb-5">
      <label for="id_password" class="font-semibold text-sm text-gray-500 block">
        Contraseña
      </label>

      {% render_field form.password type="password" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
    </div>

    <button
      type="submit"
      class="transition duration-200 bg-blue-500 hover:bg-blue-600 focus:bg-blue-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block"
    >
      <span class="inline-block mr-2">Iniciar sesión</span>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        class="w-4 h-4 inline-block"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M17 8l4 4m0 0l-4 4m4-4H3"
        />
      </svg>
    </button>
  </form>

  <div class="py-6 px-5 text-center">
    <small class="text-gray-500">
      ¿No tienes una cuenta?

      <a href="{% url 'authentication:register' %}" class="text-blue-500"> Registrate </a>
    </small>
  </div>

</div>
{% endblock %}
  

apps/authentication/templates/register.html
{% extends 'auth_layout.html' %}
{% load widget_tweaks %}
{% block title %} Registrarse {% endblock %}

{% block content %}
<h1 class="font-bold px-5 text-3xl text-gray-700 mb-5">Registrate</h1>

{% if error %}
  <div class="flex items-center py-2 px-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium block">Error!</span>
      <p>{{ error }}</p>
    </div>
  </div>
{% endif %}

<div class="bg-white shadow-sm w-full rounded-lg divide-y divide-gray-200">
  <form class="px-5 py-7" method="POST">
    {% csrf_token %}

    <div class="flex flex-col gap-2 mb-5">
      <label for="id_name" class="font-semibold text-sm text-gray-500 block">
        Nombre
      </label>

      {% render_field form.name type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" autofocus=true %}
    </div>

    <div class="flex flex-col gap-2 mb-5">
      <label for="id_email" class="font-semibold text-sm text-gray-500 block">
        Correo electrónico
      </label>

      {% render_field form.email type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
    </div>

    <div class="flex flex-col gap-2 mb-5">
      <label for="id_password" class="font-semibold text-sm text-gray-500 block">
        Contraseña
      </label>

      {% render_field form.password type="password" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
    </div>

    <button
      type="submit"
      class="transition duration-200 bg-blue-500 hover:bg-blue-600 focus:bg-blue-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block"
    >
      <span class="inline-block mr-2">Registrarse</span>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        class="w-4 h-4 inline-block"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M17 8l4 4m0 0l-4 4m4-4H3"
        />
      </svg>
    </button>
  </form>

  <div class="py-6 px-5 text-center">
    <small class="text-gray-500">
      ¿Ya tienes una cuenta?

      <a href="{% url 'authentication:login' %}" class="text-blue-500"> Inicia sesión </a>
    </small>
  </div>

</div>
{% endblock %}
    

apps/events/templates/create_event.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="flex justify-center items-start">
  <div
    class="bg-white flex flex-col w-full rounded-lg max-w-md mt-14"
  >
    <form class="px-5 py-7" method="POST">
      {% csrf_token %}

      <div class="flex flex-col gap-2 mb-5">
        <label for="id_name" class="font-semibold text-sm text-gray-500 block">
          Nombre Evento
        </label>

        {% render_field form.name type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" autofocus=true %}
      </div>


      <div class="flex flex-col gap-2 mb-5">
        <label for="id_description" class="font-semibold text-sm text-gray-500 block">
          Descripcion
        </label>

        {% render_field form.description type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
      </div>

      <div class="flex flex-col gap-2 mb-5">
        <label for="id_location" class="font-semibold text-sm text-gray-500 block">
          Ubicación
        </label>

        {% render_field form.location type="text" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
      </div>

      <div class="flex flex-col gap-2 mb-5">
        <label for="id_date_time" class="font-semibold text-sm text-gray-500 block">
          Fecha y hora
        </label>

        {% render_field form.date_time type="datetime-local" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
      </div>

      <div class="flex justify-end">
        <button
          type="submit"
          class="linear rounded-lg bg-blue-100 px-6 py-2 text-base font-medium text-brand-500 text-blue-500 transition duration-200 hover:bg-blue-200"
        >
          <span class="inline-block">Crear</span>
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

apps/events/templates/event_detail.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="flex flex-col items-center">
  <div class="w-full max-w-xl pt-10 pb-5">
    <h1 class="text-gray-600 font-semibold text-xl">Detalle del evento</h1>
  </div>

  <div class="bg-white w-full flow-root border border-gray-100 py-3 shadow-sm rounded-lg max-w-xl">
    <dl class="-my-3 divide-y divide-gray-100 text-sm">
      <div class="grid grid-cols-1 gap-1 p-3 even:bg-gray-50 sm:grid-cols-3 sm:gap-4">
        <dt class="font-medium text-gray-900">Nombre</dt>
        <dd class="text-gray-700 sm:col-span-2">{{ event.name }}</dd>
      </div>

      <div class="grid grid-cols-1 gap-1 p-3 even:bg-gray-50 sm:grid-cols-3 sm:gap-4">
        <dt class="font-medium text-gray-900">Descripcion</dt>
        <dd class="text-gray-700 sm:col-span-2">{{ event.description }}</dd>
      </div>

      <div class="grid grid-cols-1 gap-1 p-3 even:bg-gray-50 sm:grid-cols-3 sm:gap-4">
        <dt class="font-medium text-gray-900">Ubicación</dt>
        <dd class="text-gray-700 sm:col-span-2">{{ event.location }}</dd>
      </div>

      <div class="grid grid-cols-1 gap-1 p-3 even:bg-gray-50 sm:grid-cols-3 sm:gap-4">
        <dt class="font-medium text-gray-900">Fecha y hora</dt>
        <dd class="text-gray-700 sm:col-span-2">{{ event.date_time }}</dd>
      </div>

      <div class="grid grid-cols-1 gap-1 p-3 even:bg-gray-50 sm:grid-cols-3 sm:gap-4">
        <dt class="font-medium text-gray-900">Creado por</dt>
        <dd class="text-gray-700 sm:col-span-2">{{ event.user }}</dd>
      </div>
    </dl>
  </div>
</div>
{% endblock %}

apps/events/templates/event_enroll.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="flex justify-center items-start">
  <div
    class="bg-white flex flex-col w-full rounded-lg max-w-md max-h-[40rem] mt-14"
  >
    <form class="px-5 py-7" method="POST">
      {% csrf_token %}

      <div class="flex flex-col gap-2 mb-5">
        <label for="id_name" class="font-semibold text-sm text-gray-500 block">
          Elige un evento
        </label>

        {% render_field form.event class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" autofocus=true %}
      </div>

      <div class="flex flex-col gap-2 mb-5">
        <label for="id_date_time" class="font-semibold text-sm text-gray-500 block">
          Fecha y hora
        </label>

        {% render_field form.date type="datetime-local" class="outline-none border rounded-lg px-3 py-2 text-sm w-full focus:ring-1 focus:ring-blue-500 focus:border-blue-500" %}
      </div>

      <div class="flex justify-end">
        <button
          type="submit"
          class="linear rounded-lg bg-blue-100 px-6 py-2 text-base font-medium text-brand-500 text-blue-500 transition duration-200 hover:bg-blue-200"
        >
          <span class="inline-block">Inscribirse</span>
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

apps/events/templates/list_enrolled_events.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="flex flex-col">
  <div class="flex flex-col items-center justify-center">
    <div class="overflow-x-auto relative">
      <div class="flex justify-between items-center pt-10 pb-5 w-full">
        <h1 class="text-gray-600 font-semibold text-xl">Eventos que te has inscrito</h1>
      </div>

      <div class="overflow-x-auto relative shadow-sm sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
              <th scope="col" class="py-3 px-6">Nombre</th>
              <th scope="col" class="py-3 px-6">Descripcion</th>
              <th scope="col" class="py-3 px-6">Ubicación</th>
              <th scope="col" class="py-3 px-6">Fecha y hora</th>
              <th scope="col" class="py-3 px-6">Opciones</th>
            </tr>
          </thead>

          <tbody>
            {% for event in enrolled_events %}

            <tr class="bg-white border-b">
              <td class="py-4 px-6">{{ event.name }}</td>
              <td class="py-4 px-6">{{ event.description }}</td>
              <td class="py-4 px-6">{{ event.location }}</td>
              <td class="py-4 px-6">{{ event.date_time }}</td>

              <td class="py-4 px-6">
                <a href="{% url 'events:detail' event.pk %}" class="text-blue-500">
                  Ver detalle
                </a>
              </td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/events/templates/list_events.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="flex flex-col">
  <div class="flex flex-col items-center justify-center">
    <div class="overflow-x-auto relative sm:rounded-lg">
      <div class="flex justify-between items-center pt-10 pb-5 w-full">
        <h1 class="text-gray-600 font-semibold text-xl">Eventos disponibles</h1>

        <a
          href="{% url 'events:create' %}"
          class="linear rounded-lg bg-blue-100 px-4 py-2 text-base font-medium text-brand-500 text-blue-500 transition duration-200 hover:bg-blue-200"
          >Crear evento</a
        >
      </div>

      <div class="overflow-x-auto relative shadow-sm sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
              <th scope="col" class="py-3 px-6">Nombre</th>
              <th scope="col" class="py-3 px-6">Descripcion</th>
              <th scope="col" class="py-3 px-6">Ubicación</th>
              <th scope="col" class="py-3 px-6">Fecha y hora</th>
              <th scope="col" class="py-3 px-6">Opciones</th>
            </tr>
          </thead>

          <tbody>
            {% for event in events_data %}

            <tr class="bg-white border-b">
              <td class="py-4 px-6">{{ event.name }}</td>
              <td class="py-4 px-6">{{ event.description }}</td>
              <td class="py-4 px-6">{{ event.location }}</td>
              <td class="py-4 px-6">{{ event.date_time }}</td>

              <td class="py-4 px-6">
                <a href="{% url 'events:detail' event.pk %}" class="text-blue-500">
                  Ver detalle
                </a>
              </td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/auth_layout.html
<!DOCTYPE html>
<html lang="es-EC">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Events Manage | {% block title %} {% endblock %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="min-h-screen bg-gray-100">
    <main
      class="min-h-screen flex flex-col justify-center items-center lg:py-12"
    >
      <div class="p-4 md:p-10 md:w-full md:max-w-md">
        {% block content %}
        {% endblock %}
      </div>
    </main>
  </body>
</html>

core/templates/layout.html
<!DOCTYPE html>
<html lang="es-EC">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Events Manage</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
    />
  </head>
  <body class="min-h-screen bg-gray-100">
    <main class="min-h-screen px-4 md:px-0 grid md:grid-cols-[14rem_1fr] gap-5">
      <div class="hidden md:flex flex-col w-56 bg-white rounded-r-xl overflow-hidden">
        <div class="flex items-center justify-center py-10">
          <h1 class="text-2xl text-blue-600 font-semibold">Dashboard</h1>
        </div>

        <ul class="flex flex-col py-4">
          <li>
            <a
              href="{% url 'events:list' %}"
              class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800"
            >
              <span
                class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"
                ><i class="bx bx-home"></i
              ></span>
              <span class="text-sm font-medium">Todos los eventos</span>
            </a>
          </li>

          <li>
            <a
              href="{% url 'events:my_enrollments' %}"
              class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800"
            >
              <span
                class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"
                ><i class="bx bx-calendar"></i
              ></span>
              <span class="text-sm font-medium">Mis Eventos</span>
            </a>
          </li>

          <li>
            <a
              href="{% url 'events:enroll' %}"
              class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800"
            >
              <span
                class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"
                ><i class="bx bx-calendar"></i
              ></span>
              <span class="text-sm font-medium">Inscribirse</span>
            </a>
          </li>

          <li>
            <a
              href="{% url 'authentication:logout' %}"
              class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800"
            >
              <span
                class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"
                ><i class="bx bx-log-out"></i
              ></span>
              <span class="text-sm font-medium">Cerrar sesión</span>
            </a>
          </li>
        </ul>
      </div>

      {% block content %} {% endblock %}
    </main>
  </body>
</html>